In [1]:
import numpy as np
from sklearn import datasets
import tensorflow as tf


In [2]:
iris = datasets.load_iris()
x = np.array([i for i in iris.data])
y = np.array(iris.target)

In [3]:
flower_labels = ["iris setosa", "iris virginica", "iris versicolor"]

In [4]:
#one hot encoding
y = np.eye(len(set(y)))[y]

In [5]:
# normalise the x data to the range 0 to 1
x = (x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0))

In [6]:
# create indices for the train-test split
np.random.seed(42)
split = 0.8 # this makes 120 train and 30 test features
train_indices = np.random.choice(len(x), round(len(x) * split), replace=False)
test_indices =np.array(list(set(range(len(x))) - set(train_indices)))

In [7]:
# the train-test split
train_x = x[train_indices]
test_x = x[test_indices]
train_y = y[train_indices]
test_y = y[test_indices]

In [8]:
#
def prediction(train_x, test_x, train_y,k):
    print(test_x)
    d0 = tf.expand_dims(test_x, axis =1)
    d1 = tf.subtract(train_x, d0)
    d2 = tf.abs(d1)
    distances = tf.reduce_sum(input_tensor=d2, axis=2)
    print(distances)
    # or
    # distances = tf.reduce_sum(tf.abs(tf.subtract(train_x, tf.expand_dims(test_x, axis =1))), axis=2)
    _, top_k_indices = tf.nn.top_k(tf.negative(distances), k=k)
    top_k_labels = tf.gather(train_y, top_k_indices)
    predictions_sum = tf.reduce_sum(input_tensor=top_k_labels, axis=1)
    pred = tf.argmax(input=predictions_sum, axis=1)
    return pred

In [9]:
k = 5

In [10]:
i, total = 0 , 0
results = zip(prediction(train_x, test_x, train_y,k), test_y) #concatenate predicted label with actual label
print("Predicted        Actual")
print("---------        ------")
for pred, actual in results:
    print(i, flower_labels[pred.numpy()],"\t",flower_labels[np.argmax(actual)] )
    if pred.numpy() == np.argmax(actual):
        total += 1
    i += 1
accuracy = round(total/len(test_x),3)*100
print("Accuracy = ",accuracy,"%")

[[0.16666667 0.41666667 0.06779661 0.04166667]
 [0.80555556 0.41666667 0.81355932 0.625     ]
 [0.86111111 0.33333333 0.86440678 0.75      ]
 [0.66666667 0.45833333 0.77966102 0.95833333]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.66666667 0.54166667 0.79661017 1.        ]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 0.70833333 0.08474576 0.125     ]
 [0.44444444 0.41666667 0.69491525 0.70833333]
 [0.16666667 0.66666667 0.06779661 0.        ]
 [0.05555556 0.125      0.05084746 0.08333333]
 [0.27777778 0.70833333 0.08474576 0.04166667]
 [0.72222222 0.45833333 0.66101695 0.58333333]
 [0.16666667 0.16666667 0.38983051 0.375     ]
 [0.63888889 0.375      0.61016949 0.5       ]
 [0.5        0.33333333 0.50847458 0.5       ]
 [0.58333333 0.375      0.55932203 0.5       ]
 [0.55555556 0.125      0.57627119 0.5       ]
 [0.36111111 0.41666667 0.52542373 0.5       ]
 [0.33333333 0.25       0.57627119 0.45833333]
 [0.5        0.41666667 0.61016949 0.54166667]
 [0.41666667 