## Chapter 1: TensorFlow 2: eager variables and useful functions

### Importing and checking TensorFlow

In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))


TensorFlow version: 2.0.0-alpha0
Eager execution is: True
Keras version: 2.2.4-tf


#### Detect GPU:

In [2]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')


Running on CPU


### TensorFlow variables
#### Tensor Flow supports all the data types you would expect:  tf.int32 ,  tf.float64 and  tf.complex64 for example.
#### For a full list, please see: https://www.tensorflow.org/api_docs/python/tf/dtypes/DType
#### The default int type is tf.int32 and the default float type is tf.float32

#### Eager execution is the default

In [3]:
t0 = 24 # python variable
t1 = tf.Variable(42) # tensor variable
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable

In [4]:
t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

In [5]:
f1 = tf.Variable(89.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [6]:
f1.assign(98.)
f1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [7]:
f64 = tf.Variable(89, dtype = tf.float64)
f64.dtype

tf.float64

#### TensorFlow constants

In [8]:
m_o_l = tf.constant(42)
m_o_l

<tf.Tensor: id=45, shape=(), dtype=int32, numpy=42>

In [9]:
m_o_l.numpy()

42

In [10]:
unit = tf.constant(1, dtype = tf.int64)
unit

<tf.Tensor: id=48, shape=(), dtype=int64, numpy=1>

#### The rank (dimensions) of a tensor

In [11]:
tf.rank(t2)

<tf.Tensor: id=51, shape=(), dtype=int32, numpy=3>

In [12]:
tf.rank(t2).numpy()

3

#### Notice the shape of a tensor, i.e. the number of elements in each dimension

In [13]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(t2.shape)

(2, 2, 3)


#### Tensors maybe reshaped, preserving the total size,  and retain the same values,  as is often required for constructing neural networks.

In [14]:
r1 = tf.reshape(t2,[2,6]) # 2 rows 6 cols
r2 = tf.reshape(t2,[1,12]) # 1 rows 12 cols

In [15]:
r1

<tf.Tensor: id=65, shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [16]:
r2

<tf.Tensor: id=68, shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

#### Specifying an element of a tensor

In [17]:
t3 = t2[1, 0, 2] # slice 1, row 0, column 2
t3

<tf.Tensor: id=75, shape=(), dtype=float32, numpy=8.0>

#### Find the size (total number of elements)  of a tensor

In [18]:
s = tf.size(input=t2).numpy()
s

12

#### Casting tensor to numpy variable

In [19]:
print(t2.numpy())

print(t2[1, 0, 2].numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
8.0


#### Find data type of a tensor

In [20]:
t3.dtype

tf.float32

#### element wise multiplication with overloaded operator

In [21]:
t2*t2

<tf.Tensor: id=90, shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

#### Tensorflow variables support broadcasting:

In [22]:
t4 = t2*4
print(t4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


#### TensorFlow constants, transpose of a matrix and matrix multiplication, eagerly.

In [23]:
u = tf.constant([[3,4,3]])
v = tf.constant([[1,2,1]])
tf.matmul(u, tf.transpose(a=v))

<tf.Tensor: id=100, shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

#### Casting a tensor to another datatype ...

In [24]:
t1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

In [25]:
i = tf.cast(t1, dtype=tf.float32)
i

<tf.Tensor: id=105, shape=(), dtype=float32, numpy=42.0>

#### ... with truncation

In [26]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: id=108, shape=(), dtype=int32, numpy=4>

In [27]:

#adding tensors
i = tf.Variable(66)
j = tf.Variable(33)
tf.add(i,j)

<tf.Tensor: id=126, shape=(), dtype=int32, numpy=99>

#### Ragged Tensors

In [28]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [29]:
print(tf.RaggedTensor.from_row_splits(values=[5, 2, 6, 1, 4, 10, 7, 8, 6, 7],row_splits=[0, 4, 4, 7, 8, 10]))

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


###  Let's now take a look at some useful TensorFlow functions¶

In [30]:
x = [1,3,5,7,11]
y = 5
s = tf.math.squared_difference( x,  y) #() x-y)*(x-y) with broadcasting
s

<tf.Tensor: id=268, shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

### tf.reduce_mean(input_tensor,  axis=None, keepdims=None,  name=None)
#### Note that this is equivalent to np.mean, except that it infers the return data type from the input tensor whereas np.mean allows you to specify the output type, (defaulting to float64)

In [31]:
numbers = tf.constant([[4., 5.], [7., 3.]])


#### Find mean across all axes

In [32]:
tf.reduce_mean(input_tensor=numbers) #( 4. + 5. + 7. + 3.)/4 = 4.75

<tf.Tensor: id=272, shape=(), dtype=float32, numpy=4.75>

#### Find mean across columns (i.e. reduce rows)

In [33]:
tf.reduce_mean(input_tensor=numbers, axis=0) # [ (4. + 7. )/2 , (5. + 3.)/2 ].

<tf.Tensor: id=275, shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [34]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: id=278, shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

#### Find mean across rows (i.e. reduce columns)

In [35]:
tf.reduce_mean(input_tensor=numbers, axis=1) # [ (4. + 5. )/2 , (7. + 3. )/2]


<tf.Tensor: id=281, shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [36]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: id=284, shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

#### Output a tensor of the given shape filled with  values from a normal distribution.

In [37]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None)

<tf.Tensor: id=291, shape=(3, 2), dtype=float32, numpy=
array([[ 8.174752, 11.067508],
       [ 8.195847, 10.68093 ],
       [10.144283, 10.629207]], dtype=float32)>

#### Example

In [38]:
ran = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(ran)

tf.Tensor(
[[ 8.149783   8.0273695]
 [ 6.5412045 10.664776 ]
 [ 6.8243012  9.590526 ]], shape=(3, 2), dtype=float32)


In [39]:
tf.random.uniform(shape = (2,4),  minval=0, maxval=None, dtype=tf.float32, seed=None,  name=None)

<tf.Tensor: id=306, shape=(2, 4), dtype=float32, numpy=
array([[0.88165474, 0.08456266, 0.8836454 , 0.49372244],
       [0.06202447, 0.05166829, 0.01160419, 0.42806005]], dtype=float32)>

#### Output a tensor of the given shape filled with values from a uniform distribution.

#### Example

In [51]:
ran = tf.random.uniform(shape = (2,2), maxval=20, dtype=tf.int32)
print(ran)

tf.Tensor(
[[14  3]
 [11 16]], shape=(2, 2), dtype=int32)


#### To output tensors with repeatable values over runs, set a seed in tf.set_random_seeds()

In [52]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
ran2 =  tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(ran1) #Call 1
print(ran2)

tf.random.set_seed(11) #same seed
ran1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(ran1)
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### Example
#### Simulate 10 throws of two six-sided dice. Store the results
#### in a 10x3 matrix.
#### adapted for eager execution from: 
#### https://colab.research.google.com/notebooks/mlcc/creating_and_manipulating_tensors.ipynb#scrollTo=iFIOcnfz_Oqw
#### We're going to place dice throws inside two separate
#### 10x1 matrices. We could have placed dice throws inside
#### a single 10x2 matrix, but adding different columns of
#### the same matrix is tricky. We also could have placed
#### dice throws inside two 1-D tensors (vectors); doing so
#### would require transposing the result.
 

In [53]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))

  # We may add dice1 and dice2 since they share the same shape  and size.
dice_sum = dice1 + dice2

  # We've got three separate 10x1 matrices. To produce a single
  # 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1) # join in a column

print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


#### To output the index of the element  with the largest value across the axes of a tensor.

In [54]:
# 1-D tensor
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5)
i = tf.argmax(input=t5)
print('index of max; ', i)
print('Max element: ',t5[i].numpy())

i = tf.argmin(input=t5,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',t5[i].numpy())

t6 = tf.reshape(t5, [3,3])

print(t6)
i = tf.argmax(input=t6,axis=0).numpy() # max arg down rows
print('indices of max down rows; ', i)
i = tf.argmin(input=t6,axis=0).numpy() # min arg down rows
print('indices of min down rows ; ',i)

print(t6)
i = tf.argmax(input=t6,axis=1).numpy() # max arg across cols
print('indices of max across cols: ',i)
i = tf.argmin(input=t6,axis=1).numpy() # min arg across cols
print('indices of min across cols: ',i)

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max;  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  7
Min element:  -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows;  [1 0 2]
indices of min down rows ;  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max across cols:  [1 0 2]
indices of min across cols:  [0 1 1]


In [55]:
#################BEGIN CODE INCOMPATIBLE WITH TF2 because tf.contrib has gone ##################
################# need to locate integrate.odeint and fix #############################

#### integration: tf.contrib.integrate.odeint(func, y0, t, rtol=1e-06, atol = 1e-12, method=None, options=None, full_output=False, name=None)

#### examples: 

In [56]:
# solve dy/dt = 1/y # this integrates to y^2 = 2*t + 1 with the given boundary condition of y0 =1
func = lambda y,_: 1/y
tf.contrib .integrate.odeint(func, 1., [0, 1, 2],full_output=True)

AttributeError: module 'tensorflow' has no attribute 'contrib'

In [57]:
# solve `dy/dt = -y`, this integrate to  y = e^-t  (exp(-t)) with the given boundary condition of y0 =1
func = lambda y, _: -y #i.e. y = exp(-t)
tf.contrib.integrate.odeint(func, 1., [0, 1, 2]) # i.e 1, e^-1, e^-2

AttributeError: module 'tensorflow' has no attribute 'contrib'

In [58]:
#### longer example

#### The Lorenz system is a system of ordinary differential equations.
#### The Lorenz attractor is a set of chaotic solutions of the Lorenz system which, 
#### when plotted, resemble a butterfly or figure eight.

In [59]:
# eager version, adapted from https://www.tensorflow.org/versions/r1.4/api_guides/python/contrib.integrate
# restart kernel before executing this cell
import tensorflow as tf
#import tensorflow.contrib.eager as tfe
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


rho = 28.0
sigma = 10.0
beta = 8.0/3.0

def lorenz_equation(state, t):
  x, y, z = tf.unstack(state) # pop parameters off the  stack
  dx = sigma * (y - x)
  dy = x * (rho - z) - y
  dz = x * y - beta * z
  return tf.stack([dx, dy, dz]) # push parameters onto a stack

init_state = tf.constant([0, 2, 20], dtype=tf.float64)
time_intervals = np.linspace(0, 50, num=5000)
tensor_state = tf.integrate.odeint(lorenz_equation, init_state, time_intervals, full_output=False)
x, y, z = tf.transpose(a=tensor_state)

plt.plot(x, z)

AttributeError: module 'tensorflow' has no attribute 'integrate'

In [60]:
#################### END OF INCOMPATIBLE CODE ######################

#### Saving and restoring  variables


In [61]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [62]:
checkpoint.restore(save_path)
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3], dtype=int32)>

#### Creating a callable TensorFlow graph from a Python function.

In [63]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1)

x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph

assert f1(x,y).numpy() == f2(x,y).numpy()